# Generated by Django 3.2.8 on 2021-11-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='Subdescr',
        ),
        migrations.RemoveField(
            model_name='services',
            name='Subtitle',
        ),
    ]
