# Generated by Django 3.2.8 on 2021-11-10 12:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0006_projects_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Description',
            field=tinymce.models.HTMLField(default='Yes', null=True),
        ),
    ]
