# Generated by Django 3.2.8 on 2021-11-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0007_alter_projects_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='image1',
        ),
    ]
